ALTER TABLE signals ADD COLUMN IF NOT EXISTS is_signal BOOLEAN DEFAULT true;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS not_signal_reason TEXT;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS remembered JSONB;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS forgot JSONB;
