# Reddit scaled winners and other apps
reddit_wide_terms:
  "\"google photos\" \"can't find\"": 100
  "\"google photos\" \"looking for\"": 50

community_searches:
  r/googlephotos:
    "find": 60
    "looking for": 60
    "where is": 60
    "old photo": 60
  r/iphone:
    "find a photo": 40
    "can't find photo": 40
    "photos search": 40
  r/applehelp:
    "find a photo": 40
    "can't find photo": 40
    "photos search": 40
  r/ios:
    "find a photo": 40
    "can't find photo": 40
    "photos search": 40
  r/samsung:
    "gallery search": 30
    "find photo": 30
  r/GalaxyS24:
    "gallery search": 30
    "find photo": 30

tournament:
  searchPosts: true
  searchComments: true
  searchSort: "relevance"
  maxCommentsCount: 3
